name: Process Figma Tokens PR

on: 
  push:
    branches:
      - 'figma-tokens'
    paths:
      - 'src/tokens/tokens.json'
jobs:
  process_tokens:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # checkout to the head of this PR
      - uses: actions/checkout@master
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
        
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache dependencies
        uses: actions/cache@v2
        id: yrn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
          
      - name: Install dependencies
        run: |
          yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Run token-transformer
        run: yarn tokens
        
        
      - name: Create PR 
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Tokens updated"
          title: "Design tokens updated"
          body: "Design tokens have been updated via Figma and need to be reviewed."
          branch: design-tokens-review
          base: main

